sonar.projectKey=fleet-management
sonar.organization=yakymivdanylo
sonar.projectName=Fleet Management
sonar.sources=src
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.venv/**,**/__pycache__/**
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage-api.xml,coverage-worker.xml
