apiVersion: v1
kind: Secret
metadata:
  name: fleet-secret
  namespace: fleet-management
  labels:
    app.kubernetes.io/part-of: fleet-management
type: Opaque             
stringData:              
  POSTGRES_PASSWORD: "lab-only-pg-pass"
  RABBITMQ_DEFAULT_USER: "fleet"
  RABBITMQ_DEFAULT_PASS: "lab-only-mq-pass"
  JWT_SECRET_KEY: "lab-only-jwt-key-not-for-production"