services:
  db:
    image: postgres:16
    container_name: fleet_management_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: fleet_password
      POSTGRES_DB: fleet_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: