"""Secrets-trap crash test for the gitleaks pre-commit hook (Lab 3, task 3).

plant  - write demo/payment_gateway.py with a hardcoded SYNTHETIC token (random, issued by
         nobody, grants access to nothing) -> staging it must make the hook FAIL.
fix    - move the value into the git-ignored .env, read it from the environment instead and
         document the variable in .env.example -> the hook must PASS.
clean  - remove the demo file and the .env line.

The token is generated on every `plant`, so no secret-looking literal lives in the repo.
"""

import argparse
import secrets
import string
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEMO_FILE = ROOT / "demo" / "payment_gateway.py"
ENV_FILE = ROOT / ".env"
ENV_EXAMPLE = ROOT / ".env.example"
VAR = "PAYMENT_GATEWAY_TOKEN"

HARDCODED = '''"""Payment gateway client settings (secrets-trap demo)."""

# SYNTHETIC test value generated by scripts/secrets_trap.py - not a real credential.
{var} = "{token}"
'''

FROM_ENV = '''"""Payment gateway client settings (secrets-trap demo)."""

import os

{var} = os.getenv("{var}", "")
'''


def _synthetic_token() -> str:
    alphabet = string.ascii_letters + string.digits
    return "sk_test_" + "".join(secrets.choice(alphabet) for _ in range(32))


def _env_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines() if path.exists() else []


def _write_lines(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def plant() -> None:
    DEMO_FILE.parent.mkdir(exist_ok=True)
    DEMO_FILE.write_text(HARDCODED.format(var=VAR, token=_synthetic_token()), encoding="utf-8")
    print(f"Planted synthetic secret in {DEMO_FILE.relative_to(ROOT)}")


def fix() -> None:
    prefix = f'{VAR} = "'
    hardcoded = [
        line
        for line in DEMO_FILE.read_text(encoding="utf-8").splitlines()
        if line.startswith(prefix)
    ]
    if not hardcoded:
        raise SystemExit(f"No hardcoded {VAR} in {DEMO_FILE} - run `plant` first")
    token = hardcoded[0][len(prefix) : -1]

    env = [line for line in _env_lines(ENV_FILE) if not line.startswith(f"{VAR}=")]
    _write_lines(ENV_FILE, [*env, f"{VAR}={token}"])

    example = _env_lines(ENV_EXAMPLE)
    if not any(line.startswith(f"{VAR}=") for line in example):
        _write_lines(ENV_EXAMPLE, [*example, f"{VAR}="])

    DEMO_FILE.write_text(FROM_ENV.format(var=VAR), encoding="utf-8")
    print(f"{VAR} moved to .env (git-ignored); {DEMO_FILE.relative_to(ROOT)} reads os.getenv")


def clean() -> None:
    DEMO_FILE.unlink(missing_ok=True)
    if DEMO_FILE.parent.exists() and not any(DEMO_FILE.parent.iterdir()):
        DEMO_FILE.parent.rmdir()
    if ENV_FILE.exists():
        _write_lines(ENV_FILE, [ln for ln in _env_lines(ENV_FILE) if not ln.startswith(f"{VAR}=")])
    print("Secrets-trap demo files removed")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("action", choices=["plant", "fix", "clean"])
    {"plant": plant, "fix": fix, "clean": clean}[parser.parse_args().action]()


if __name__ == "__main__":
    main()
